# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\3Dspiral\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = GLViewWidget(self.groupBox)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.horizontalSlider_h = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_h.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_h.setObjectName("horizontalSlider_h")
        self.gridLayout.addWidget(self.horizontalSlider_h, 4, 5, 1, 1)
        self.horizontalSlider_r = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_r.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r.setObjectName("horizontalSlider_r")
        self.gridLayout.addWidget(self.horizontalSlider_r, 3, 5, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 7, 4, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 3, 4, 1, 1)
        self.doubleSpinBox_plots_l = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_plots_l.setDecimals(0)
        self.doubleSpinBox_plots_l.setMaximum(100000000.0)
        self.doubleSpinBox_plots_l.setProperty("value", 1000.0)
        self.doubleSpinBox_plots_l.setObjectName("doubleSpinBox_plots_l")
        self.gridLayout.addWidget(self.doubleSpinBox_plots_l, 7, 2, 1, 1)
        self.doubleSpinBox_h_l = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_h_l.setDecimals(1)
        self.doubleSpinBox_h_l.setMaximum(100000000.0)
        self.doubleSpinBox_h_l.setSingleStep(0.1)
        self.doubleSpinBox_h_l.setProperty("value", 10.0)
        self.doubleSpinBox_h_l.setObjectName("doubleSpinBox_h_l")
        self.gridLayout.addWidget(self.doubleSpinBox_h_l, 4, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 4, 4, 1, 1)
        self.doubleSpinBox_rrc_l = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_rrc_l.setDecimals(3)
        self.doubleSpinBox_rrc_l.setMaximum(1.0)
        self.doubleSpinBox_rrc_l.setSingleStep(0.001)
        self.doubleSpinBox_rrc_l.setObjectName("doubleSpinBox_rrc_l")
        self.gridLayout.addWidget(self.doubleSpinBox_rrc_l, 6, 2, 1, 1)
        self.doubleSpinBox_l_l = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_l_l.setDecimals(3)
        self.doubleSpinBox_l_l.setMaximum(100000000.0)
        self.doubleSpinBox_l_l.setSingleStep(0.001)
        self.doubleSpinBox_l_l.setObjectName("doubleSpinBox_l_l")
        self.gridLayout.addWidget(self.doubleSpinBox_l_l, 5, 2, 1, 1)
        self.doubleSpinBox_r_u = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_r_u.setDecimals(1)
        self.doubleSpinBox_r_u.setMaximum(100000000.0)
        self.doubleSpinBox_r_u.setSingleStep(0.1)
        self.doubleSpinBox_r_u.setProperty("value", 20.0)
        self.doubleSpinBox_r_u.setObjectName("doubleSpinBox_r_u")
        self.gridLayout.addWidget(self.doubleSpinBox_r_u, 3, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 5, 4, 1, 1)
        self.doubleSpinBox_l_u = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_l_u.setDecimals(3)
        self.doubleSpinBox_l_u.setMaximum(100000000.0)
        self.doubleSpinBox_l_u.setSingleStep(0.001)
        self.doubleSpinBox_l_u.setObjectName("doubleSpinBox_l_u")
        self.gridLayout.addWidget(self.doubleSpinBox_l_u, 5, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 6, 4, 1, 1)
        self.doubleSpinBox_h_u = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_h_u.setDecimals(1)
        self.doubleSpinBox_h_u.setMaximum(100000000.0)
        self.doubleSpinBox_h_u.setSingleStep(0.1)
        self.doubleSpinBox_h_u.setProperty("value", 10.0)
        self.doubleSpinBox_h_u.setObjectName("doubleSpinBox_h_u")
        self.gridLayout.addWidget(self.doubleSpinBox_h_u, 4, 3, 1, 1)
        self.doubleSpinBox_plots_u = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_plots_u.setDecimals(0)
        self.doubleSpinBox_plots_u.setMaximum(100000000.0)
        self.doubleSpinBox_plots_u.setProperty("value", 1000.0)
        self.doubleSpinBox_plots_u.setObjectName("doubleSpinBox_plots_u")
        self.gridLayout.addWidget(self.doubleSpinBox_plots_u, 7, 3, 1, 1)
        self.doubleSpinBox_rrc_u = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_rrc_u.setDecimals(3)
        self.doubleSpinBox_rrc_u.setMaximum(1.0)
        self.doubleSpinBox_rrc_u.setSingleStep(0.001)
        self.doubleSpinBox_rrc_u.setObjectName("doubleSpinBox_rrc_u")
        self.gridLayout.addWidget(self.doubleSpinBox_rrc_u, 6, 3, 1, 1)
        self.doubleSpinBox_rrc_v = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_rrc_v.setDecimals(3)
        self.doubleSpinBox_rrc_v.setMaximum(1.0)
        self.doubleSpinBox_rrc_v.setSingleStep(0.001)
        self.doubleSpinBox_rrc_v.setObjectName("doubleSpinBox_rrc_v")
        self.gridLayout.addWidget(self.doubleSpinBox_rrc_v, 6, 1, 1, 1)
        self.doubleSpinBox_r_l = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_r_l.setDecimals(1)
        self.doubleSpinBox_r_l.setMaximum(100000000.0)
        self.doubleSpinBox_r_l.setSingleStep(0.1)
        self.doubleSpinBox_r_l.setProperty("value", 20.0)
        self.doubleSpinBox_r_l.setObjectName("doubleSpinBox_r_l")
        self.gridLayout.addWidget(self.doubleSpinBox_r_l, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(0, 24))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 1, 1, 1)
        self.doubleSpinBox_n_v = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_n_v.setDecimals(1)
        self.doubleSpinBox_n_v.setMaximum(100000000.0)
        self.doubleSpinBox_n_v.setSingleStep(0.1)
        self.doubleSpinBox_n_v.setProperty("value", 5.0)
        self.doubleSpinBox_n_v.setObjectName("doubleSpinBox_n_v")
        self.gridLayout.addWidget(self.doubleSpinBox_n_v, 2, 1, 1, 1)
        self.doubleSpinBox_n_u = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_n_u.setDecimals(1)
        self.doubleSpinBox_n_u.setMaximum(100000000.0)
        self.doubleSpinBox_n_u.setSingleStep(0.1)
        self.doubleSpinBox_n_u.setProperty("value", 5.0)
        self.doubleSpinBox_n_u.setObjectName("doubleSpinBox_n_u")
        self.gridLayout.addWidget(self.doubleSpinBox_n_u, 2, 3, 1, 1)
        self.doubleSpinBox_plots_v = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_plots_v.setDecimals(0)
        self.doubleSpinBox_plots_v.setMaximum(100000000.0)
        self.doubleSpinBox_plots_v.setProperty("value", 1000.0)
        self.doubleSpinBox_plots_v.setObjectName("doubleSpinBox_plots_v")
        self.gridLayout.addWidget(self.doubleSpinBox_plots_v, 7, 1, 1, 1)
        self.horizontalSlider_n = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_n.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_n.setObjectName("horizontalSlider_n")
        self.gridLayout.addWidget(self.horizontalSlider_n, 2, 5, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 4, 1, 1)
        self.doubleSpinBox_r_v = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_r_v.setDecimals(1)
        self.doubleSpinBox_r_v.setMaximum(100000000.0)
        self.doubleSpinBox_r_v.setSingleStep(0.1)
        self.doubleSpinBox_r_v.setProperty("value", 20.0)
        self.doubleSpinBox_r_v.setObjectName("doubleSpinBox_r_v")
        self.gridLayout.addWidget(self.doubleSpinBox_r_v, 3, 1, 1, 1)
        self.doubleSpinBox_n_l = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_n_l.setDecimals(1)
        self.doubleSpinBox_n_l.setMaximum(100000000.0)
        self.doubleSpinBox_n_l.setSingleStep(0.1)
        self.doubleSpinBox_n_l.setProperty("value", 5.0)
        self.doubleSpinBox_n_l.setObjectName("doubleSpinBox_n_l")
        self.gridLayout.addWidget(self.doubleSpinBox_n_l, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 4, 1, 1)
        self.doubleSpinBox_l_v = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_l_v.setDecimals(3)
        self.doubleSpinBox_l_v.setMaximum(100000000.0)
        self.doubleSpinBox_l_v.setSingleStep(0.001)
        self.doubleSpinBox_l_v.setObjectName("doubleSpinBox_l_v")
        self.gridLayout.addWidget(self.doubleSpinBox_l_v, 5, 1, 1, 1)
        self.doubleSpinBox_h_v = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_h_v.setDecimals(1)
        self.doubleSpinBox_h_v.setMaximum(100000000.0)
        self.doubleSpinBox_h_v.setSingleStep(0.1)
        self.doubleSpinBox_h_v.setProperty("value", 10.0)
        self.doubleSpinBox_h_v.setObjectName("doubleSpinBox_h_v")
        self.gridLayout.addWidget(self.doubleSpinBox_h_v, 4, 1, 1, 1)
        self.horizontalSlider_rrc = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_rrc.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_rrc.setObjectName("horizontalSlider_rrc")
        self.gridLayout.addWidget(self.horizontalSlider_rrc, 6, 5, 1, 1)
        self.horizontalSlider_plots = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_plots.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_plots.setObjectName("horizontalSlider_plots")
        self.gridLayout.addWidget(self.horizontalSlider_plots, 7, 5, 1, 1)
        self.horizontalSlider_l = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_l.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_l.setObjectName("horizontalSlider_l")
        self.gridLayout.addWidget(self.horizontalSlider_l, 5, 5, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_animarion = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_animarion.setObjectName("pushButton_animarion")
        self.horizontalLayout.addWidget(self.pushButton_animarion)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 5, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "プロット"))
        self.groupBox_2.setTitle(_translate("MainWindow", "パラーメータ"))
        self.label.setText(_translate("MainWindow", "巻数"))
        self.label_2.setText(_translate("MainWindow", "半径"))
        self.label_5.setText(_translate("MainWindow", "プロット数"))
        self.label_3.setText(_translate("MainWindow", "高さ"))
        self.label_6.setText(_translate("MainWindow", "中央半径減少率"))
        self.label_4.setText(_translate("MainWindow", "長さ"))
        self.label_8.setText(_translate("MainWindow", "上限"))
        self.label_10.setText(_translate("MainWindow", "項目"))
        self.label_7.setText(_translate("MainWindow", "下限"))
        self.label_12.setText(_translate("MainWindow", "値"))
        self.label_9.setText(_translate("MainWindow", "固定"))
        self.pushButton_animarion.setText(_translate("MainWindow", "アニメーション"))

from pyqtgraph.opengl import GLViewWidget
